version: '3.1'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - "3306:3306"
    - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: testing

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080